//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdH_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class frauds
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_incident { get; set; }
        public string lieu_incident { get; set; }
        public Nullable<byte> zone { get; set; }
        public Nullable<byte> pays { get; set; }
        public Nullable<byte> gravite_incident { get; set; }
        public Nullable<byte> responsabilite_tdh { get; set; }
        public string resume_incident { get; set; }
        public Nullable<byte> nature_de_lincident_nature { get; set; }
        public string nature_de_lincident_autre { get; set; }
        public string nature_de_lincident_estimation_du_montant { get; set; }
        public string details_de_lincident { get; set; }
        public Nullable<byte> preuves_significatives_signalement_superieur_hierarchique { get; set; }
        public Nullable<System.DateTime> preuves_significatives_signalement_superieur_hierarchique_date { get; set; }
        public Nullable<byte> preuves_significatives_une_implication_externe { get; set; }
        public Nullable<System.DateTime> preuves_significatives_une_implication_externe_date { get; set; }
        public Nullable<byte> preuves_significatives_avec_quelle_instance { get; set; }
        public string preuves_significatives_si_autre { get; set; }
        public string mesures_prises_par_la_delegation { get; set; }
        public string recommandations_du_delegue_et_ou_de_la_personne_en_charge_des_finances { get; set; }
        public string personnes_impliquees_expatrie { get; set; }
        public string personnes_impliquees_consultant_prestataire_expatrie { get; set; }
        public string personnes_impliquees_staff_national_tdh { get; set; }
        public string personnes_impliquees_consultant_prestataire_local { get; set; }
        public string personnes_impliquees_tiers { get; set; }
        public string personnes_impliquees_nombre_total_de_personnes_impliquees { get; set; }
        public Nullable<byte> incident_demande_suivi { get; set; }
        public string incident_demande_suivi_type { get; set; }
        public Nullable<byte> support_necessaire { get; set; }
        public string support_necessaire_type { get; set; }
        public string rapport_rempli_par { get; set; }
        public Nullable<System.DateTime> date_de_lenvoi_au_siege { get; set; }
        public string rapport_traite_par { get; set; }
        public string mise_a_jour_du_cas { get; set; }
        public Nullable<System.DateTime> mise_a_jour_du_cas_date { get; set; }
        public string a_remplir_par_le_siege_numero_de_lincident { get; set; }
        public Nullable<byte> a_remplir_par_le_siege_recu_par { get; set; }
        public string a_remplir_par_le_siege_recu_par_autre { get; set; }
        public string a_remplir_par_le_siege_traite_au_siege_par { get; set; }
        public string a_remplir_par_le_siege_montant_chf { get; set; }
        public string a_remplir_par_le_siege_mise_a_jour_recommandation { get; set; }
        public Nullable<System.DateTime> a_remplir_par_le_siege_date_de_fermeture { get; set; }
        public Nullable<byte> a_remplir_par_le_siege_statut { get; set; }
        public Nullable<int> annee { get; set; }
        public Nullable<int> langue { get; set; }
    }
}
