//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdH_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pse
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> date_incident { get; set; }
        public string lieu_incident { get; set; }
        public Nullable<byte> zone { get; set; }
        public Nullable<byte> pays { get; set; }
        public Nullable<byte> gravite_incident { get; set; }
        public Nullable<byte> responsabilite_tdh { get; set; }
        public string resume_incident { get; set; }
        public Nullable<byte> violence_physique { get; set; }
        public Nullable<byte> violence_physique_nature { get; set; }
        public string violence_physique_autre { get; set; }
        public Nullable<byte> violence_sexuelle { get; set; }
        public Nullable<byte> violence_sexuelle_nature { get; set; }
        public string violence_sexuelle_autre { get; set; }
        public Nullable<byte> violence_psychologique { get; set; }
        public Nullable<byte> violence_psychologique_nature { get; set; }
        public string violence_psychologique_autre { get; set; }
        public Nullable<byte> negligence { get; set; }
        public Nullable<byte> negligence_nature { get; set; }
        public string negligence_autre { get; set; }
        public string details_de_lincident { get; set; }
        public Nullable<byte> victime_enfant_statut { get; set; }
        public string victime_enfant_nom { get; set; }
        public Nullable<System.DateTime> victime_enfant_date_de_naissance { get; set; }
        public Nullable<byte> victime_enfant_age { get; set; }
        public Nullable<byte> victime_enfant_sexe { get; set; }
        public string victime_enfant_adresse { get; set; }
        public string victime_enfant_handicap { get; set; }
        public string victime_enfant_autre_information_importante { get; set; }
        public Nullable<byte> agresseur_statut { get; set; }
        public string agresseur_nom { get; set; }
        public string agresseur_position { get; set; }
        public Nullable<byte> agresseur_age { get; set; }
        public Nullable<byte> agresseur_sexe { get; set; }
        public string agresseur_statut_familial { get; set; }
        public string agresseur_nom_de_lemployeur { get; set; }
        public string agresseur_lien_avec_tdh { get; set; }
        public string agresseur_lien_avec_lenfant { get; set; }
        public string agresseur_autre_information_importante { get; set; }
        public string personne_signalant_nom { get; set; }
        public string personne_signalant_position { get; set; }
        public string personne_signalant_adresse { get; set; }
        public string personne_signalant_nom_de_lemployeur { get; set; }
        public string personne_signalant_lien_avec_tdh { get; set; }
        public string personne_signalant_lien_avec_lenfant { get; set; }
        public string personne_signalant_autre_information_importante { get; set; }
        public string mesures_prises_pour_proteger_lenfant { get; set; }
        public string mesures_prises_pour_eviter_la_recidive { get; set; }
        public string mesures_prises_pour_proteger_laction_de_tdh { get; set; }
        public string informations_supplementaires_quest_ce_que_lenfant_souhaite { get; set; }
        public string informations_supplementaires_de_quel_soutien_lenfant_a_t_il_besoin { get; set; }
        public string informations_supplementaires_qui_doit_apporter_ce_soutien { get; set; }
        public Nullable<byte> informations_supplementaires_y_a_t_il_dautres_actions { get; set; }
        public string informations_supplementaires_qui_quand { get; set; }
        public string informations_supplementaires_qui_va_suivre { get; set; }
        public string informations_supplementaires_lecons_apprises { get; set; }
        public string recommandations_du_delegue { get; set; }
        public string rapport_rempli_par { get; set; }
        public Nullable<System.DateTime> date_de_lenvoi_au_siege { get; set; }
        public string rapport_traite_par { get; set; }
        public string mise_a_jour_du_cas { get; set; }
        public Nullable<System.DateTime> mise_a_jour_du_cas_date { get; set; }
        public string a_remplir_par_le_siege_numero_de_lincident { get; set; }
        public Nullable<byte> a_remplir_par_le_siege_recu_par { get; set; }
        public string a_remplir_par_le_siege_recu_par_autre { get; set; }
        public string a_remplir_par_le_siege_traite_au_siege_par { get; set; }
        public string a_remplir_par_le_siege_mise_a_jour_recommandation { get; set; }
        public Nullable<System.DateTime> a_remplir_par_le_siege_date_de_fermeture { get; set; }
        public Nullable<byte> a_remplir_par_le_siege_statut { get; set; }
        public Nullable<int> annee { get; set; }
        public Nullable<int> langue { get; set; }
    }
}
