//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdH_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class securities
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> date_incident { get; set; }
        public string lieu_incident { get; set; }
        public Nullable<byte> zone { get; set; }
        public Nullable<byte> pays { get; set; }
        public Nullable<byte> gravite_incident { get; set; }
        public Nullable<byte> responsabilite_tdh { get; set; }
        public string resume_incident { get; set; }
        public Nullable<byte> sante { get; set; }
        public Nullable<byte> sante_employe { get; set; }
        public Nullable<byte> sante_nature { get; set; }
        public string sante_autre { get; set; }
        public Nullable<byte> accident_lie_au_deplacement { get; set; }
        public Nullable<byte> accident_lie_au_deplacement_nature { get; set; }
        public string accident_lie_au_deplacement_autre { get; set; }
        public Nullable<byte> maintenance_du_bureau { get; set; }
        public Nullable<byte> maintenance_du_bureau_nature { get; set; }
        public string maintenance_du_bureau_autre { get; set; }
        public Nullable<byte> catastrophe_naturelle { get; set; }
        public Nullable<byte> catastrophe_naturelle_nature { get; set; }
        public string catastrophe_naturelle_autre { get; set; }
        public Nullable<byte> degat_materiel { get; set; }
        public Nullable<byte> degat_materiel_nature { get; set; }
        public string degat_materiel_autre { get; set; }
        public Nullable<byte> surete_autre { get; set; }
        public string surete_autre_description { get; set; }
        public Nullable<byte> menace { get; set; }
        public Nullable<byte> menace_envers { get; set; }
        public string menace_envers_autre { get; set; }
        public Nullable<byte> menace_nature { get; set; }
        public string menace_nature_autre { get; set; }
        public Nullable<byte> agression { get; set; }
        public Nullable<byte> agression_employe { get; set; }
        public Nullable<byte> agression_nature { get; set; }
        public string agression_autre { get; set; }
        public Nullable<byte> enlevement { get; set; }
        public Nullable<byte> enlevement_employe { get; set; }
        public Nullable<byte> enlevement_nature { get; set; }
        public string enlevement_autre { get; set; }
        public Nullable<byte> vol_intrusion { get; set; }
        public Nullable<byte> vol_intrusion_nature { get; set; }
        public string vol_intrusion_autre { get; set; }
        public Nullable<byte> attaque { get; set; }
        public Nullable<byte> attaque_nature { get; set; }
        public string attaque_autre { get; set; }
        public Nullable<byte> troubles_publics { get; set; }
        public Nullable<byte> troubles_publics_nature { get; set; }
        public string troubles_publics_autre { get; set; }
        public Nullable<byte> securite_autre { get; set; }
        public string securite_autre_desctiption { get; set; }
        public string details_de_lincident { get; set; }
        public string raisons_de_la_presence_de_tdh { get; set; }
        public string mesures_prises_par_la_delegation { get; set; }
        public string recommandations_du_delegue { get; set; }
        public string personnes_impliquees_expatrie { get; set; }
        public string personnes_impliquees_consultant_prestataire_expatrie { get; set; }
        public string personnes_impliquees_staff_national_tdh { get; set; }
        public string personnes_impliquees_consultant_prestataire_local { get; set; }
        public string personnes_impliquees_tiers { get; set; }
        public string personnes_impliquees_nombre_total_de_personnes { get; set; }
        public Nullable<byte> implication_exterieure_police { get; set; }
        public Nullable<byte> implication_exterieure_juge_de_paix { get; set; }
        public Nullable<byte> implication_exterieure_tiers_population { get; set; }
        public Nullable<byte> implication_exterieure_hopital_centre_de_sante { get; set; }
        public Nullable<byte> implication_exterieure_compagnie_dassurance { get; set; }
        public Nullable<byte> implication_exterieure_aucune { get; set; }
        public Nullable<byte> implication_exterieure_autre { get; set; }
        public string implication_exterieure_autre_description { get; set; }
        public Nullable<byte> impact_sur_le_programme_hibernation { get; set; }
        public Nullable<byte> impact_sur_le_programme_nb_de_jours { get; set; }
        public Nullable<byte> impact_sur_le_programme_evacuation { get; set; }
        public Nullable<byte> impact_sur_le_programme_nb_de_personnes { get; set; }
        public Nullable<byte> impact_sur_le_programme_evacuation_medicale { get; set; }
        public Nullable<byte> impact_sur_le_programme_nb_de_jours_sans_travailler { get; set; }
        public Nullable<byte> impact_sur_le_programme_cout_financier { get; set; }
        public string impact_sur_le_programme_montant_approximatif { get; set; }
        public Nullable<byte> impact_sur_le_programme_suivi_judicaire { get; set; }
        public Nullable<byte> impact_sur_le_programme_autre { get; set; }
        public Nullable<byte> impact_sur_le_programme_aucun { get; set; }
        public string impact_sur_le_programme_autre_description { get; set; }
        public Nullable<byte> incident_demande_suivi { get; set; }
        public string incident_demande_suivi_type { get; set; }
        public Nullable<byte> support_necessaire { get; set; }
        public string support_necessaire_type { get; set; }
        public Nullable<byte> plan_securite_change { get; set; }
        public Nullable<byte> plan_securite_envoyer_au_siege { get; set; }
        public Nullable<System.DateTime> plan_securite_envoyer_au_siege_date { get; set; }
        public string rapport_rempli_par { get; set; }
        public Nullable<System.DateTime> date_de_lenvoi_au_siege { get; set; }
        public string rapport_traite_par { get; set; }
        public string mise_a_jour_du_cas { get; set; }
        public Nullable<System.DateTime> mise_a_jour_du_cas_date { get; set; }
        public string a_remplir_par_le_siege_numero_de_lincident { get; set; }
        public Nullable<byte> a_remplir_par_le_siege_recu_par { get; set; }
        public string a_remplir_par_le_siege_recu_par_autre { get; set; }
        public string a_remplir_par_le_siege_traite_au_siege_par { get; set; }
        public string a_remplir_par_le_siege_mise_a_jour_recommandation { get; set; }
        public Nullable<byte> a_remplir_par_le_siege_statut { get; set; }
        public Nullable<System.DateTime> a_remplir_par_le_siege_date_de_fermeture { get; set; }
        public Nullable<int> annee { get; set; }
        public Nullable<int> langue { get; set; }
    }
}
