//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdH_2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tdhEntities : DbContext
    {
        public tdhEntities()
            : base("name=tdhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<frauds> frauds { get; set; }
        public virtual DbSet<Langues> Langues { get; set; }
        public virtual DbSet<Listes> Listes { get; set; }
        public virtual DbSet<pse> pse { get; set; }
        public virtual DbSet<securities> securities { get; set; }
        public virtual DbSet<Traductions> Traductions { get; set; }
    }
}
