//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdH_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traductions
    {
        public int IDTraductions { get; set; }
        public int FK_Listes { get; set; }
        public int FK_Langues { get; set; }
        public int Valeur { get; set; }
        public string Traduction { get; set; }
    
        public virtual Langues Langues { get; set; }
        public virtual Listes Listes { get; set; }
    }
}
